version: 2.1

orbs:
  slack: circleci/slack@4.1

commands:
  on-failed-notification:
    description: The notification on failed
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
  slack-notification:
    description: The slack notification
    steps:
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
      - on-faied-notification

jobs:
  lint:
    docker:
      - image: circleci/node:16.13
    steps:
      - checkout
      - restore_cache:
          keys: ["node_modules"]
      - run:
          name: install dependencies
          command: |
            npm install
      - run:
          name: linting code
          command: |
            npm run lint
      - save_cache:
          paths: ["node_modules"]
          key: "node_modules"
      - on-failed-notification


  # build

  # create-docker-image

  # deploy-k8s-cluster

  # deploy-app-to-k8s

workflows:
  default:
    jobs:
      - lint:
          context: slack-secrets

