version: 2.1

orbs:
  slack: circleci/slack@4.1

commands:
  on-failed-notification:
    description: The notification on failed
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
  slack-notification:
    description: The slack notification
    steps:
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
      - on-faied-notification

jobs:
  lint:
    docker:
      - image: circleci/node:16.13
    steps:
      - checkout
      - restore_cache:
          keys: ["node_modules"]
      - run:
          name: install dependencies
          command: |
            npm install
      - run:
          name: linting code
          command: |
            npm run lint
      - save_cache:
          paths: ["node_modules"]
          key: "node_modules"
      - on-failed-notification

  create-docker-image:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1 curl jq
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Build application Docker image
          command: |
            docker build -t ${DOCKERHUB_USERNAME}/udacity-capstone:${CIRCLE_WORKFLOW_ID:0:7} .
      - run: 
          name: Publish Docker Image to Docker Hub
          command: |
            echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" - password-stdin
            docker push ${DOCKERHUB_USERNAME}/udacity-capstone:${CIRCLE_WORKFLOW_ID:0:7}
      - on-failed-notification

  # deploy-k8s-cluster

  # deploy-app-to-k8s

workflows:
  default:
    jobs:
      - lint:
          context: slack-secrets
      - create-docker-image:
          context: slack-secrets

